"""add course_id to users

Revision ID: 1684367c1041
Revises: 44ee2dda5ded
Create Date: 2026-06-20 13:12:39.566334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1684367c1041'
down_revision: Union[str, Sequence[str], None] = '44ee2dda5ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course_id')
    # ### end Alembic commands ###
