"""add enrollments table

Revision ID: 9680e3bce09d
Revises: b4fb051a83b4
Create Date: 2026-06-14 19:00:14.144438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9680e3bce09d'
down_revision: Union[str, Sequence[str], None] = 'b4fb051a83b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.alter_column('contents', 'content_text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('learning_units', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('progress', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('progress', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_progress_id'), table_name='progress')
    op.create_foreign_key(None, 'progress', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.create_index(op.f('ix_progress_id'), 'progress', ['id'], unique=False)
    op.drop_column('progress', 'completed_at')
    op.drop_column('progress', 'user_id')
    op.drop_column('learning_units', 'duration_minutes')
    op.alter_column('contents', 'content_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
